version: 2
jobs:
  build:
    working_directory: /go/src/github.com/likecoin/likechain
    docker:
      - image: circleci/golang:1.11.2
    environment:
      - GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          key: likechain-deps-{{ .Branch }}-{{ checksum "go.mod" }}-{{ checksum "Makefile" }}
          paths:
            - /go/pkg/mod
      - run:
          name: Install dependencies
          command: |
            make get_vendor_deps
      - save_cache:
          key: likechain-deps-{{ .Branch }}-{{ checksum "go.mod" }}-{{ checksum "Makefile" }}
          paths:
            - /go/pkg/mod
      - run:
          name: Unit testing
          command: make test
      - run:
          name: Submit codecov
          command: bash <(curl -s https://codecov.io/bash)
